[2025-10-15 15:07:08,309][flwr][WARNING] - DEPRECATED FEATURE: flwr.simulation.start_simulation() is deprecated.
	Instead, use the `flwr run` CLI command to start a local simulation in your Flower app, as shown for example below:

		$ flwr new  # Create a new Flower app from a template

		$ flwr run  # Run the Flower app in Simulation Mode

	Using `start_simulation()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
[2025-10-15 15:07:08,309][flwr][INFO] - Starting Flower simulation, config: num_rounds=1, no round_timeout
[2025-10-15 15:07:09,746][flwr][INFO] - Flower VCE: Ray initialized with resources: {'CPU': 20.0, 'memory': 18656577946.0, 'node:__internal_head__': 1.0, 'object_store_memory': 7995676262.0, 'node:10.100.14.161': 1.0}
[2025-10-15 15:07:09,746][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2025-10-15 15:07:09,746][flwr][INFO] - No `client_resources` specified. Using minimal resources for clients.
[2025-10-15 15:07:09,747][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 1, 'num_gpus': 0.0}
[2025-10-15 15:07:09,803][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 20 actors
[2025-10-15 15:07:09,803][flwr][INFO] - [INIT]
[2025-10-15 15:07:09,803][flwr][INFO] - Requesting initial parameters from one random client
[2025-10-15 15:07:11,208][flwr][INFO] - Received initial parameters from one random client
[2025-10-15 15:07:11,208][flwr][INFO] - Starting evaluation of initial global parameters
[2025-10-15 15:07:11,727][flwr][INFO] - initial parameters (loss, other metrics): 182.25914406776428, {'accuracy': 0.0975}
[2025-10-15 15:07:11,728][flwr][INFO] - 
[2025-10-15 15:07:11,728][flwr][INFO] - [ROUND 1]
[2025-10-15 15:07:11,728][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 100)
[2025-10-15 15:07:12,248][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=22824, ip=10.100.14.161, actor_id=8605ae02e8cb4bb5cc105ad301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f10144e5010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22824, ip=10.100.14.161, actor_id=8605ae02e8cb4bb5cc105ad301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f10144e5010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable

[2025-10-15 15:07:12,249][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=22824, ip=10.100.14.161, actor_id=8605ae02e8cb4bb5cc105ad301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f10144e5010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22824, ip=10.100.14.161, actor_id=8605ae02e8cb4bb5cc105ad301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f10144e5010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable
[2025-10-15 15:07:13,164][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=22825, ip=10.100.14.161, actor_id=51b9bdebcb30f9e5f975251e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3bcc3e1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22825, ip=10.100.14.161, actor_id=51b9bdebcb30f9e5f975251e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3bcc3e1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable

[2025-10-15 15:07:13,164][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=22825, ip=10.100.14.161, actor_id=51b9bdebcb30f9e5f975251e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3bcc3e1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22825, ip=10.100.14.161, actor_id=51b9bdebcb30f9e5f975251e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3bcc3e1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable
[2025-10-15 15:07:13,227][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=22822, ip=10.100.14.161, actor_id=383ddef781fa9e517fe2d00801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb1dc5ed010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22822, ip=10.100.14.161, actor_id=383ddef781fa9e517fe2d00801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb1dc5ed010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable

[2025-10-15 15:07:13,228][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=22822, ip=10.100.14.161, actor_id=383ddef781fa9e517fe2d00801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb1dc5ed010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22822, ip=10.100.14.161, actor_id=383ddef781fa9e517fe2d00801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb1dc5ed010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable
[2025-10-15 15:07:13,305][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=22813, ip=10.100.14.161, actor_id=e506730cad6cd8965d194f5f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb3883e1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22813, ip=10.100.14.161, actor_id=e506730cad6cd8965d194f5f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb3883e1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable

[2025-10-15 15:07:13,305][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=22813, ip=10.100.14.161, actor_id=e506730cad6cd8965d194f5f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb3883e1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22813, ip=10.100.14.161, actor_id=e506730cad6cd8965d194f5f01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb3883e1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable
[2025-10-15 15:07:13,374][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=22826, ip=10.100.14.161, actor_id=38d9116906ccd57833d986b101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7efeb41d1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22826, ip=10.100.14.161, actor_id=38d9116906ccd57833d986b101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7efeb41d1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable

[2025-10-15 15:07:13,374][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=22826, ip=10.100.14.161, actor_id=38d9116906ccd57833d986b101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7efeb41d1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22826, ip=10.100.14.161, actor_id=38d9116906ccd57833d986b101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7efeb41d1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable
[2025-10-15 15:07:13,406][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=22814, ip=10.100.14.161, actor_id=8d421cf6c35486f0b3a5b54a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f32c0049010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22814, ip=10.100.14.161, actor_id=8d421cf6c35486f0b3a5b54a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f32c0049010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable

[2025-10-15 15:07:13,407][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=22814, ip=10.100.14.161, actor_id=8d421cf6c35486f0b3a5b54a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f32c0049010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22814, ip=10.100.14.161, actor_id=8d421cf6c35486f0b3a5b54a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f32c0049010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable
[2025-10-15 15:07:13,454][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=22819, ip=10.100.14.161, actor_id=43bd3513e64666d35762145001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1de0371010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22819, ip=10.100.14.161, actor_id=43bd3513e64666d35762145001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1de0371010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable

[2025-10-15 15:07:13,454][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=22819, ip=10.100.14.161, actor_id=43bd3513e64666d35762145001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1de0371010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22819, ip=10.100.14.161, actor_id=43bd3513e64666d35762145001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1de0371010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable
[2025-10-15 15:07:13,498][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=22812, ip=10.100.14.161, actor_id=7acfa3e5b415a2678a2d057001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f41100d5010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22812, ip=10.100.14.161, actor_id=7acfa3e5b415a2678a2d057001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f41100d5010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable

[2025-10-15 15:07:13,498][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=22812, ip=10.100.14.161, actor_id=7acfa3e5b415a2678a2d057001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f41100d5010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22812, ip=10.100.14.161, actor_id=7acfa3e5b415a2678a2d057001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f41100d5010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable
[2025-10-15 15:07:13,567][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=22823, ip=10.100.14.161, actor_id=15915d5ca84e0d860a6a928b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feea8041010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22823, ip=10.100.14.161, actor_id=15915d5ca84e0d860a6a928b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feea8041010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable

[2025-10-15 15:07:13,567][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=22823, ip=10.100.14.161, actor_id=15915d5ca84e0d860a6a928b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feea8041010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22823, ip=10.100.14.161, actor_id=15915d5ca84e0d860a6a928b01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7feea8041010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable
[2025-10-15 15:07:13,804][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=22811, ip=10.100.14.161, actor_id=f68f0936943243974574c38501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f652873d010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22811, ip=10.100.14.161, actor_id=f68f0936943243974574c38501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f652873d010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable

[2025-10-15 15:07:13,804][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=22811, ip=10.100.14.161, actor_id=f68f0936943243974574c38501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f652873d010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 48, in fit
    optim = torch.optim.SGD(self.model.parameters, lr=lr, momentum=momentum)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/sgd.py", line 65, in __init__
    super().__init__(params, defaults)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/torch/optim/optimizer.py", line 393, in __init__
    param_groups = list(params)
TypeError: 'method' object is not iterable

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=22811, ip=10.100.14.161, actor_id=f68f0936943243974574c38501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f652873d010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'method' object is not iterable
[2025-10-15 15:07:13,804][flwr][INFO] - aggregate_fit: received 0 results and 10 failures
[2025-10-15 15:07:14,287][flwr][INFO] - fit progress: (1, 182.25914406776428, {'accuracy': 0.0975}, 2.558985646999645)
[2025-10-15 15:07:14,287][flwr][INFO] - configure_evaluate: strategy sampled 25 clients (out of 100)
[2025-10-15 15:07:16,939][flwr][INFO] - aggregate_evaluate: received 25 results and 0 failures
[2025-10-15 15:07:16,939][flwr][WARNING] - No evaluate_metrics_aggregation_fn provided
[2025-10-15 15:07:16,939][flwr][INFO] - 
[2025-10-15 15:07:16,939][flwr][INFO] - [SUMMARY]
[2025-10-15 15:07:16,939][flwr][INFO] - Run finished 1 round(s) in 5.21s
[2025-10-15 15:07:16,940][flwr][INFO] - 	History (loss, distributed):
[2025-10-15 15:07:16,940][flwr][INFO] - 		round 1: 6.91625262260437
[2025-10-15 15:07:16,940][flwr][INFO] - 	History (loss, centralized):
[2025-10-15 15:07:16,940][flwr][INFO] - 		round 0: 182.25914406776428
[2025-10-15 15:07:16,940][flwr][INFO] - 		round 1: 182.25914406776428
[2025-10-15 15:07:16,940][flwr][INFO] - 	History (metrics, centralized):
[2025-10-15 15:07:16,940][flwr][INFO] - 	{'accuracy': [(0, 0.0975), (1, 0.0975)]}
[2025-10-15 15:07:16,940][flwr][INFO] - 
