[2025-10-16 10:32:11,747][flwr][WARNING] - DEPRECATED FEATURE: flwr.simulation.start_simulation() is deprecated.
	Instead, use the `flwr run` CLI command to start a local simulation in your Flower app, as shown for example below:

		$ flwr new  # Create a new Flower app from a template

		$ flwr run  # Run the Flower app in Simulation Mode

	Using `start_simulation()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
[2025-10-16 10:32:11,747][flwr][INFO] - Starting Flower simulation, config: num_rounds=1, no round_timeout
[2025-10-16 10:32:16,973][flwr][INFO] - Flower VCE: Ray initialized with resources: {'CPU': 20.0, 'node:__internal_head__': 1.0, 'object_store_memory': 8469739929.0, 'memory': 19762726503.0, 'node:10.100.14.161': 1.0}
[2025-10-16 10:32:16,974][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2025-10-16 10:32:16,974][flwr][INFO] - No `client_resources` specified. Using minimal resources for clients.
[2025-10-16 10:32:16,974][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 1, 'num_gpus': 0.0}
[2025-10-16 10:32:18,400][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 20 actors
[2025-10-16 10:32:18,401][flwr][INFO] - [INIT]
[2025-10-16 10:32:18,401][flwr][INFO] - Requesting initial parameters from one random client
[2025-10-16 10:32:19,968][flwr][INFO] - Received initial parameters from one random client
[2025-10-16 10:32:19,968][flwr][INFO] - Starting evaluation of initial global parameters
[2025-10-16 10:32:21,087][flwr][INFO] - initial parameters (loss, other metrics): 181.88856101036072, {'accuracy': 0.0984}
[2025-10-16 10:32:21,087][flwr][INFO] - 
[2025-10-16 10:32:21,087][flwr][INFO] - [ROUND 1]
[2025-10-16 10:32:21,087][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 100)
[2025-10-16 10:32:21,597][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=5401, ip=10.100.14.161, actor_id=8b5767769ba9d48b86f4749001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fc788289010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5401, ip=10.100.14.161, actor_id=8b5767769ba9d48b86f4749001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fc788289010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

[2025-10-16 10:32:21,597][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=5401, ip=10.100.14.161, actor_id=8b5767769ba9d48b86f4749001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fc788289010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5401, ip=10.100.14.161, actor_id=8b5767769ba9d48b86f4749001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fc788289010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'
[2025-10-16 10:32:22,463][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=5403, ip=10.100.14.161, actor_id=fedccd060282150236d0ac8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f05d8161010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5403, ip=10.100.14.161, actor_id=fedccd060282150236d0ac8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f05d8161010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

[2025-10-16 10:32:22,463][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=5403, ip=10.100.14.161, actor_id=fedccd060282150236d0ac8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f05d8161010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5403, ip=10.100.14.161, actor_id=fedccd060282150236d0ac8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f05d8161010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'
[2025-10-16 10:32:22,567][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=5405, ip=10.100.14.161, actor_id=56ef28d4af17ccf7bd987f4a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fccbc2d9010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5405, ip=10.100.14.161, actor_id=56ef28d4af17ccf7bd987f4a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fccbc2d9010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

[2025-10-16 10:32:22,567][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=5405, ip=10.100.14.161, actor_id=56ef28d4af17ccf7bd987f4a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fccbc2d9010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5405, ip=10.100.14.161, actor_id=56ef28d4af17ccf7bd987f4a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fccbc2d9010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'
[2025-10-16 10:32:22,597][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=5402, ip=10.100.14.161, actor_id=2e9662b41fcde7a9ea3a60bd01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f13585c9010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5402, ip=10.100.14.161, actor_id=2e9662b41fcde7a9ea3a60bd01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f13585c9010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

[2025-10-16 10:32:22,598][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=5402, ip=10.100.14.161, actor_id=2e9662b41fcde7a9ea3a60bd01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f13585c9010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5402, ip=10.100.14.161, actor_id=2e9662b41fcde7a9ea3a60bd01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f13585c9010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'
[2025-10-16 10:32:22,666][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=5399, ip=10.100.14.161, actor_id=0c8df8536ad4b5065f31923801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f29902d9010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5399, ip=10.100.14.161, actor_id=0c8df8536ad4b5065f31923801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f29902d9010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

[2025-10-16 10:32:22,666][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=5399, ip=10.100.14.161, actor_id=0c8df8536ad4b5065f31923801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f29902d9010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5399, ip=10.100.14.161, actor_id=0c8df8536ad4b5065f31923801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f29902d9010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'
[2025-10-16 10:32:22,726][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=5398, ip=10.100.14.161, actor_id=3acf4689d63b8c3504fa088201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7efbb03e1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5398, ip=10.100.14.161, actor_id=3acf4689d63b8c3504fa088201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7efbb03e1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

[2025-10-16 10:32:22,726][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=5398, ip=10.100.14.161, actor_id=3acf4689d63b8c3504fa088201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7efbb03e1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5398, ip=10.100.14.161, actor_id=3acf4689d63b8c3504fa088201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7efbb03e1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'
[2025-10-16 10:32:22,787][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=5391, ip=10.100.14.161, actor_id=63296859d932d133c142b30301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3c5c231010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5391, ip=10.100.14.161, actor_id=63296859d932d133c142b30301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3c5c231010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

[2025-10-16 10:32:22,787][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=5391, ip=10.100.14.161, actor_id=63296859d932d133c142b30301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3c5c231010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5391, ip=10.100.14.161, actor_id=63296859d932d133c142b30301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3c5c231010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'
[2025-10-16 10:32:22,824][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=5392, ip=10.100.14.161, actor_id=571d63faff578fe80264527101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f54e44d1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5392, ip=10.100.14.161, actor_id=571d63faff578fe80264527101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f54e44d1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

[2025-10-16 10:32:22,824][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=5392, ip=10.100.14.161, actor_id=571d63faff578fe80264527101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f54e44d1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5392, ip=10.100.14.161, actor_id=571d63faff578fe80264527101000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f54e44d1010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'
[2025-10-16 10:32:22,896][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=5408, ip=10.100.14.161, actor_id=22507cf5e14c3ce4f2ecee7301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f6304741010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5408, ip=10.100.14.161, actor_id=22507cf5e14c3ce4f2ecee7301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f6304741010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

[2025-10-16 10:32:22,896][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=5408, ip=10.100.14.161, actor_id=22507cf5e14c3ce4f2ecee7301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f6304741010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5408, ip=10.100.14.161, actor_id=22507cf5e14c3ce4f2ecee7301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f6304741010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'
[2025-10-16 10:32:23,074][flwr][ERROR] - Traceback (most recent call last):
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 95, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        partition_id_str, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 401, in get_client_result
    return self._fetch_future_result(cid)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 282, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
                                         ~~~~~~~^
        future
        ^^^^^^
    )  # type: (str, Message, Context)
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 2962, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ~~~~~~~~~~~~~~~~~~^
        object_refs, timeout=timeout, _tensor_transport=_tensor_transport
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=5393, ip=10.100.14.161, actor_id=df0ba91551b5b535790eb67501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7e54731010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5393, ip=10.100.14.161, actor_id=df0ba91551b5b535790eb67501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7e54731010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

[2025-10-16 10:32:23,074][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=5393, ip=10.100.14.161, actor_id=df0ba91551b5b535790eb67501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7e54731010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/mamatha/ME/Research/Hands-On/flower_tutorial/client.py", line 51, in fit
    optim = torch.optim.SGD(self.get_parameters(), lr=lr, momentum=momentum)
                            ~~~~~~~~~~~~~~~~~~~^^
TypeError: FlowerClient.get_parameters() missing 1 required positional argument: 'config'

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=5393, ip=10.100.14.161, actor_id=df0ba91551b5b535790eb67501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7e54731010>)
  File "/home/mamatha/anaconda3/lib/python3.13/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: FlowerClient.get_parameters() missing 1 required positional argument: 'config'
[2025-10-16 10:32:23,075][flwr][INFO] - aggregate_fit: received 0 results and 10 failures
[2025-10-16 10:32:23,569][flwr][INFO] - fit progress: (1, 181.88856101036072, {'accuracy': 0.0984}, 2.481433011000263)
[2025-10-16 10:32:23,569][flwr][INFO] - configure_evaluate: strategy sampled 25 clients (out of 100)
[2025-10-16 10:32:26,181][flwr][INFO] - aggregate_evaluate: received 25 results and 0 failures
[2025-10-16 10:32:26,181][flwr][WARNING] - No evaluate_metrics_aggregation_fn provided
[2025-10-16 10:32:26,181][flwr][INFO] - 
[2025-10-16 10:32:26,181][flwr][INFO] - [SUMMARY]
[2025-10-16 10:32:26,181][flwr][INFO] - Run finished 1 round(s) in 5.09s
[2025-10-16 10:32:26,181][flwr][INFO] - 	History (loss, distributed):
[2025-10-16 10:32:26,182][flwr][INFO] - 		round 1: 6.902084913253784
[2025-10-16 10:32:26,182][flwr][INFO] - 	History (loss, centralized):
[2025-10-16 10:32:26,182][flwr][INFO] - 		round 0: 181.88856101036072
[2025-10-16 10:32:26,182][flwr][INFO] - 		round 1: 181.88856101036072
[2025-10-16 10:32:26,182][flwr][INFO] - 	History (metrics, centralized):
[2025-10-16 10:32:26,182][flwr][INFO] - 	{'accuracy': [(0, 0.0984), (1, 0.0984)]}
[2025-10-16 10:32:26,182][flwr][INFO] - 
